### PR TITLE
Update composer in Dockerfile

### PR DESCRIPTION
**Pull request by tomasnorre**
The `make composer` command wasn't working any more, after update composer to latest release 2.4.4 it works again.

### CODE REVIEW

**Comment by Crell** [comment]
I really wish there was a more stable way of doing that...

**Comment by tomasnorre** [comment]
That I can understand, I'll push a better PR.

**Comment by tomasnorre** [comment]
Remembered a better way. I have updated the PHP version too, as 8.1.0 was a little old. So using 8.1 now.

**Comment by Crell** [comment]
Holy tacos, I didn't know that works!  I like that way better than the mess I had before. :smile:

**Comment by tomasnorre** [comment]
I remember seeing something like it in the TYPO3 GmbH Dockerfiles, but had forgotten about at the first PR.

**Pull request merged**
