### PR TITLE
Change link length

### PR DESCRIPTION
**Pull request by tomasnorre**
This changes the link length, to match more modern browsers. We ran into limits on planet.typo3.org with the 255 length.

### CODE REVIEW

**Comment by Crell** [comment]
I've no objection here, but do we need a migration of some kind to update existing sites?

**Comment by tomasnorre** [comment]
That I have already taken care of. We are currently deploying with the branch used for this PR. So that is taken care of. When this gets merged, I can switch back to the original repository.

**Comment by Crell** [comment]
Yes, but for non-TYPO3 Planet users.

**Comment by tomasnorre** [comment]
That's true. As there are no migrations included in this repository at all. I did the migrations in the planet-typo3 project. 

Perhaps adding migrations to this repository, would be an Idea. Otherwise, how would you ensure such changes in the future?

**Comment by Crell** [comment]
Yes.  Can you add one to the PR? :smile:

**Comment by tomasnorre** [comment]
Sure, will take care of that beginning next week. I'll add both migrations, so that the migrations here reflects the repository completely. Not just the latest change.

**Comment by Crell** [comment]
Bumping?  @tomasnorre ?

**Comment by tomasnorre** [comment]
Sorry, forgot about it. Have pushed them now. I have kept the timestamps on files, as they were in the planet.typo3.org project. But as no migrations existed yet. It should do no harm.

**Comment by tomasnorre** [comment]
I don't get why the CI still fails, I have added the intl extension to the GitHub Action too.
I cannot look more into this atm. Will be back 28th of December, might find some time there.

**Comment by tomasnorre** [comment]
The CI problem was the `ext-intl` package name was wrong. I have fixed it in this commit. So the main branch should be green again after the merge.

**Comment by Crell** [comment]
Thanks, Tomas!

**Comment by tomasnorre** [comment]
You're Welcome.

**Pull request merged**
